events {}

http {
    upstream ayurveda_upstream {
        server app:8000;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name _;
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;
        client_max_body_size 10m;
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header Referrer-Policy strict-origin-when-cross-origin always;

        location /static/ {
            proxy_pass http://ayurveda_upstream;
            expires 1d;
        }

        location / {
            proxy_pass http://ayurveda_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
