const REPLACEMENTS = [
  ["triphala churna", "Triphala Churna"],
  ["triphala guggulu", "Triphala Guggulu"],
  ["yogaraj guggulu", "Yogaraj Guggulu"],
  ["mahayogaraj", "Mahayogaraj Guggulu"],
  ["kaishor guggulu", "Kaishor Guggulu"],
  ["kanchanar", "Kanchanar Guggulu"],
  ["arogyavardhini", "Arogyavardhini Vati"],
  ["chandraprabha", "Chandraprabha vati"],
  ["raktamokshana", "Raktamokshana"],
  ["chyawanprash", "Chyawanprash"],
  ["chyavanprash", "Chyawanprash"],
  ["shankhpushpi", "Shankhpushpi"],
  ["shankpushpi", "Shankhpushpi"],
  ["dashamool", "Dashamoola"],
  ["dashmool", "Dashamoola"],
  ["shirodhara", "Shirodhara"],
  ["panchakarma", "Panchakarma"],
  ["panchkarma", "Panchakarma"],
  ["dinacharya", "Dinacharya"],
  ["ritucharya", "Ritucharya"],
  ["trifala", "Triphala"],
  ["triphla", "Triphala"],
  ["ashwaganda", "Ashwagandha"],
  ["ashwagandha", "Ashwagandha"],
  ["shatavri", "Shatavari"],
  ["shatawari", "Shatavari"],
  ["vaata", "Vata"],
  ["vaat", "Vata"],
  ["pita", "Pitta"],
  ["pitta", "Pitta"],
  ["kafa", "Kapha"],
  ["kaaf", "Kapha"],
  ["agni", "Agni"],
  ["aama", "Ama"],
  ["aam", "Ama"],
  ["prakritti", "Prakriti"],
  ["prakirti", "Prakriti"],
  ["vikritti", "Vikriti"],
  ["vikruti", "Vikriti"],
  ["ojas", "Ojas"],
  ["tejas", "Tejas"],
  ["prana", "Prana"],
  ["dhatu", "Dhatu"],
  ["mala", "Mala"],
  ["srotas", "Srotas"],
  ["abhyanga", "Abhyanga"],
  ["nasya", "Nasya"],
  ["basti", "Basti"],
  ["virechana", "Virechana"],
  ["vamana", "Vamana"],
  ["brahmi", "Brahmi"],
  ["guduchi", "Guduchi"],
  ["giloy", "Giloy"],
  ["neem", "Neem"],
  ["turmeric", "Haridra"],
  ["haridra", "Haridra"],
  ["ginger", "Shunthi"],
  ["shunthi", "Shunthi"],
  ["pippali", "Pippali"],
  ["trikatu", "Trikatu"],
  ["amalaki", "Amalaki"],
  ["amla", "Amalaki"],
  ["bibhitaki", "Bibhitaki"],
  ["haritaki", "Haritaki"],
  ["chaturmukha", "Chaturmukha"],
  ["arjuna", "Arjuna"],
  ["punarnava", "Punarnava"],
  ["gokshura", "Gokshura"],
  ["gokhru", "Gokshura"],
  ["varunadi", "Varunadi"],
  ["yashtimadhu", "Yashtimadhu"],
  ["mulethi", "Yashtimadhu"],
  ["jatamansi", "Jatamansi"],
  ["mandukaparni", "Mandukaparni"],
  ["tagara", "Tagara"],
  ["musta", "Musta"],
  ["shilajit", "Shilajit"],
  ["guggul", "Guggulu"],
  ["guggulu", "Guggulu"],
  ["hingvastak", "Hingvastaka"],
  ["hingvashtak", "Hingvastaka"],
  ["sitopaladi", "Sitopaladi"],
  ["talisadi", "Talisadi"],
  ["lavangadi", "Lavangadi"],
  ["godanti", "Godanti"],
  ["sutshekhar", "Sutshekhar"],
  ["sutsekhar", "Sutshekhar"],
  ["kamdudha", "Kamdudha"],
  ["praval", "Praval"],
  ["mukta", "Mukta"],
  ["ashokarishta", "Ashokarishta"],
  ["dashmoolarishta", "Dashamoolarishta"],
  ["dashamoolarishta", "Dashamoolarishta"],
  ["kumaryasava", "Kumaryasava"],
  ["punarnavasava", "Punarnavasava"],
  ["arjunarishta", "Arjunarishta"],
  ["drakshasava", "Drakshasava"],
  ["saraswatarishta", "Saraswatarishta"],
  ["balarishta", "Balarishta"],
  ["lohasava", "Lohasava"],
  ["takra", "Takra"],
  ["ghrita", "Ghrita"],
  ["ghee", "Ghrita"],
  ["kashaya", "Kashaya"],
  ["kwath", "Kwatha"],
  ["kadha", "Kwatha"],
  ["choorna", "Churna"],
  ["churna", "Churna"],
  ["vati", "Vati"],
  ["gutika", "Gutika"],
  ["avaleha", "Avaleha"],
  ["lehya", "Lehya"],
  ["bhasma", "Bhasma"],
  ["pishti", "Pishti"],
  ["rasayan", "Rasayana"],
  ["rasayana", "Rasayana"],
  ["vajikarana", "Vajikarana"],
  ["medhya", "Medhya"],
  ["hridya", "Hridya"],
  ["deepan", "Deepana"],
  ["dipan", "Deepana"],
  ["pachan", "Pachana"],
  ["anuloman", "Anulomana"],
  ["grahi", "Grahi"],
  ["brimhana", "Brimhana"],
  ["langhana", "Langhana"],
  ["lekhana", "Lekhana"],
  ["stambhana", "Stambhana"],
  ["shodhana", "Shodhana"],
  ["shamana", "Shamana"],
  ["vedanasthapana", "Vedanasthapana"],
  ["krimighna", "Krimighna"],
  ["kushtaghna", "Kushtaghna"],
  ["jwaraghna", "Jwaraghna"],
  ["kasahara", "Kasahara"],
  ["shwasahara", "Shwasahara"],
  ["amlapitta", "Amlapitta"],
  ["agnimandya", "Agnimandya"],
  ["ajirna", "Ajirna"],
  ["grahani", "Grahani"],
  ["udarroga", "Udararoga"],
  ["amavata", "Amavata"],
  ["sandhivata", "Sandhivata"],
  ["gridhrasi", "Gridhrasi"],
  ["katigraha", "Katigraha"],
  ["manyakasthambha", "Manyakasthambha"],
  ["pakshaghata", "Pakshaghata"],
  ["ardita", "Ardita"],
  ["apasmara", "Apasmara"],
  ["unmada", "Unmada"],
  ["panduroga", "Panduroga"],
  ["kamala", "Kamala"],
  ["mutrakrichra", "Mutrakrichra"],
  ["mutraghata", "Mutraghata"],
  ["prameha", "Prameha"],
  ["madhumeha", "Madhumeha"],
  ["yonivyapad", "Yonivyapad"],
  ["rajakshma", "Rajayakshma"],
  ["shoola", "Shoola"],
  ["aruchi", "Aruchi"],
  ["atisara", "Atisara"],
  ["pravahika", "Pravahika"],
  ["udavarta", "Udavarta"],
  ["udgara", "Udgara"],
  ["anaha", "Anaha"],
  ["halimaka", "Halimaka"],
  ["tamaka shwasa", "Tamaka Shwasa"],
  ["shwasa", "Shwasa"],
  ["kasa", "Kasa"],
  ["pinasa", "Pinasa"],
  ["pratishyaya", "Pratishyaya"],
  ["karnaroga", "Karnaroga"],
  ["netraroga", "Netraroga"],
  ["mukhapaka", "Mukhapaka"],
  ["vrana", "Vrana"],
  ["dushta vrana", "Dushta Vrana"],
  ["bhagandara", "Bhagandara"],
  ["arsha", "Arsha"],
  ["udarda", "Udarda"],
  ["sheetapitta", "Sheetapitta"],
  ["visarpa", "Visarpa"],
  ["dadru", "Dadru"],
  ["kitibha", "Kitibha"],
  ["eka kushta", "Eka Kushta"],
];

const SORTED_REPLACEMENTS = [...REPLACEMENTS].sort((a, b) => b[0].length - a[0].length);

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function correctAyurvedicTerms(transcript) {
  let corrected = String(transcript || "");
  for (const [raw, canonical] of SORTED_REPLACEMENTS) {
    corrected = corrected.replace(new RegExp(`(?<!\\w)${escapeRegExp(raw)}(?!\\w)`, "gi"), canonical);
  }
  return corrected;
}

module.exports = { correctAyurvedicTerms, REPLACEMENTS };
